export type GerberType = 'copper' | 'soldermask' | 'silkscreen' | 'solderpaste' | 'drill' | 'outline' | null;
export type GerberSide = 'top' | 'bottom' | 'inner' | 'all' | null;

export interface GerberProps {
    type: GerberType;
    side: GerberSide;
}

import promisify from 'pify';
import { unzip as _unzip } from 'fflate';
import stackup, { type InputLayer, type Stackup } from 'pcb-stackup';
import { renderGerbersZip } from 'gerbers-renderer';
import { Buffer } from 'buffer';

import JSZip from 'jszip';

const unzip = promisify(_unzip);

export async function renderWithGerbersRenderer(file: File): Promise<{ top?: { svg: string }; bottom?: { svg: string } } | null> {
    try {
        console.log("[GerberExtraction] Rendering with gerbers-renderer package...");
        const result = await renderGerbersZip(file);
        if (result && result.layers) {
            let topSvg = "";
            let bottomSvg = "";
            
            // Extract top/bottom layer SVGs or board previews if generated by viewer
            if (typeof result.layers.top === "string") topSvg = result.layers.top;
            else if (result.layers.top?.svg) topSvg = result.layers.top.svg;
            
            if (typeof result.layers.bottom === "string") bottomSvg = result.layers.bottom;
            else if (result.layers.bottom?.svg) bottomSvg = result.layers.bottom.svg;

            if (topSvg || bottomSvg) {
                return {
                    ...(topSvg ? { top: { svg: topSvg } } : {}),
                    ...(bottomSvg ? { bottom: { svg: bottomSvg } } : {})
                };
            }
        }
    } catch (err) {
        console.warn("[GerberExtraction] gerbers-renderer direct zip rendering error/fallback:", err);
    }
    return null;
}

export async function loadLayers(file: File): Promise<InputLayer[]> {
    console.log(`[GerberExtraction] Starting layer extraction for file: "${file.name}" (Size: ${(file.size / 1024).toFixed(2)} KB)`);
    try {
        const buffer = await file.arrayBuffer();
        const ext = file.name.split('.').pop()?.toLowerCase();
        console.log(`[GerberExtraction] Detected file extension: "${ext}"`);

        let archiveBytes = new Uint8Array(buffer);

        if (ext === 'rar') {
            console.log(`[GerberExtraction] Attempting JSZip load for file with .rar extension...`);
            try {
                const zip = new JSZip();
                await zip.loadAsync(buffer);
                const generated = await zip.generateAsync({ type: 'uint8array' });
                archiveBytes = new Uint8Array(generated);
                console.log(`[GerberExtraction] JSZip successfully unpacked file with .rar extension.`);
            } catch (rarErr) {
                console.log(`[GerberExtraction] File is not a ZIP formatted archive (JSZip load skipped). Proceeding to fflate...`, rarErr);
            }
        }

        console.log(`[GerberExtraction] Unzipping archive via fflate...`);
        const entries = await unzip(archiveBytes);
        console.log(`[GerberExtraction] fflate unzipped ${Object.keys(entries).length} file entries from archive.`);
        
        const layers = await readLayers(entries);
        console.log(`[GerberExtraction] Successfully parsed ${layers.length} valid Gerber/Drill layers.`);
        return layers;
    } catch (err: any) {
        console.error(`[GerberExtraction Error] Failed during extraction process:`, err);
        return [];
    }
}

export async function readLayers(entries: Record<string, Uint8Array>): Promise<InputLayer[]> {
    const layers = <InputLayer[]>[];
    const entryNames = Object.keys(entries);
    console.log(`[GerberExtraction] Inspecting ${entryNames.length} file entries in archive:`, entryNames);

    for (const name of entryNames) {
        // Skip hidden files, system files, or directory entries
        if (name.startsWith('__MACOSX') || name.startsWith('.') || name.includes('/.') || name.endsWith('/')) {
            continue;
        }

        const ext = name.split('.').pop()?.toLowerCase() || '';
        // Skip obvious non-gerber documents & images
        if (['pdf', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'csv', 'bom', 'doc', 'docx', 'xlsx', 'xls', 'zip', 'rar', '7z', 'html', 'json'].includes(ext)) {
            continue;
        }

        const { type, side } = mapLayerType(name);
        console.log(`[GerberExtraction] File entry "${name}" mapped -> type: ${type || 'NULL'}, side: ${side || 'NULL'}`);
        if (type !== null) {
            layers.push({ type, side, gerber: Buffer.from(entries[name]), filename: name });
        }
    }
    return layers;
}

export function mapLayerType(name: string): GerberProps {
    let type: GerberType = null;
    let side: GerberSide = null;

    const lowerName = name.toLowerCase();
    const segments = lowerName.split(/_|-|\./);
    const ext = segments[segments.length - 1];

    switch (ext) {
        case 'gtl': return { type: 'copper', side: 'top' };
        case 'gto': return { type: 'silkscreen', side: 'top' };
        case 'gtp': return { type: 'solderpaste', side: 'top' };
        case 'gts': return { type: 'soldermask', side: 'top' };
        case 'gbl': return { type: 'copper', side: 'bottom' };
        case 'gbo': return { type: 'silkscreen', side: 'bottom' };
        case 'gbp': return { type: 'solderpaste', side: 'bottom' };
        case 'gbs': return { type: 'soldermask', side: 'bottom' };
        case 'gko': case 'gml': case 'gm1': case 'gm2': case 'gm3': case 'g1': return { type: 'outline', side: 'all' };
        case 'drl': case 'txt': case 'xln': case 'drd': return { type: 'drill', side: 'all' };
        default:
            if (/^g[1-8]$/i.test(ext) || /^g[1-8]l$/i.test(ext) || /^in[1-8]$/i.test(ext) || /^l[1-8]$/i.test(ext) || /^gl[1-8]$/i.test(ext)) {
                return { type: 'copper', side: 'inner' };
            }
            break;
    }

    if (segments.some(s => s.includes('edge') || s.includes('outline') || s.includes('border') || s.includes('profile') || s.includes('cutout') || s.includes('keepout'))) {
        return { type: 'outline', side: 'all' };
    }

    if (segments.some(s => s.includes('drill') || s.includes('hole') || s.includes('drl') || s.includes('nc'))) {
        return { type: 'drill', side: 'all' };
    }

    if (segments.includes('sm') || segments.some(s => s.includes('mask') || s.includes('soldermask'))) {
        type = 'soldermask';
    } else if (segments.includes('sp') || segments.some(s => s.includes('paste') || s.includes('solderpaste'))) {
        type = 'solderpaste';
    } else if (segments.includes('ss') || segments.some(s => s.includes('silk') || s.includes('silkscreen') || s.includes('legend'))) {
        type = 'silkscreen';
    } else if (segments.includes('cu') || segments.some(s => s.includes('copper') || s.includes('art') || s.includes('layer'))) {
        type = 'copper';
    }

    if (segments.some(s => s.startsWith('in'))) {
        side = 'inner';
    } else if (segments.includes('f') || segments.some(s => s.includes('top') || s.includes('front') || s.includes('cmp'))) {
        side = 'top';
    } else if (segments.includes('b') || segments.some(s => s.includes('bottom') || s.includes('back') || s.includes('sol'))) {
        side = 'bottom';
    }

    if (side === 'inner' && !type) {
        type = 'copper';
    }

    return { type, side };
}

export const COLORS: Record<string, [string, string]> = {
    'green': ['#004200bf', '#ffffff'],
    'red': ['#b20000bf', '#ffffff'],
    'yellow': ['#ff9900bf', '#ffffff'],
    'blue': ['#004284bf', '#ffffff'],
    'white': ['#ffffffbf', '#000000'],
    'black': ['#000000bf', '#ffffff'],
    'purple': ['#480084bf', '#ffffff'],
};

export const FINISHES: Record<string, string> = {
    'gold': '#cc9933',
    'tin': '#f5f5f5',
};

export const PASTE = '#999999';

export type RenderSide = 'top' | 'bottom';
export type RenderSolderMask = keyof typeof COLORS;
export type RenderCopperFinish = keyof typeof FINISHES;

export interface RenderOptions {
    sm: RenderSolderMask;
    cf: RenderCopperFinish;
    sp: boolean;
}

export async function renderStack(layers: InputLayer[], options: RenderOptions): Promise<Stackup<string, InputLayer>> {
    if (!layers || layers.length === 0) {
        return { top: null, bottom: null, layers: [] } as any;
    }

    const [sm, ss] = COLORS[options.sm] || COLORS['green'];
    const sp = options.sp ? PASTE : 'transparent';
    const cf = FINISHES[options.cf] || FINISHES['tin'];

    try {
        return await stackup(layers, {
            color: { sm, ss, sp, cf },
        });
    } catch (err) {
        console.warn("Gerber parser stackup error caught safely:", err);
        return { top: null, bottom: null, layers: [] } as any;
    }
}

